"""init

Revision ID: 9c08bdc2c8bd
Revises: 
Create Date: 2021-06-18 00:09:53.179609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c08bdc2c8bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('update_request', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('secret', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Users_version',
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('update_request', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('secret', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_Users_version_end_transaction_id'), 'Users_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_Users_version_operation_type'), 'Users_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_Users_version_transaction_id'), 'Users_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_Users_version_transaction_id'), table_name='Users_version')
    op.drop_index(op.f('ix_Users_version_operation_type'), table_name='Users_version')
    op.drop_index(op.f('ix_Users_version_end_transaction_id'), table_name='Users_version')
    op.drop_table('Users_version')
    op.drop_table('Users')
    # ### end Alembic commands ###
